version: '3'

networks:
    networks:

volumes:
    website: 
        driver_opts: 
            type: none
            o: bind
            device: /home/kankim/data/wp
    database: 
        driver_opts: 
            type: none
            o: bind
            device: /home/kankim/data/db

services:
    nginx:
        depends_on: 
            - wordpress
        build: ./requirements/nginx
        image: nginx:kankim
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - type: volume
              source: website
              target: /var/www/
        networks:
            - networks
        tty: true
        env_file: 
            - .env

    wordpress:
        depends_on: 
            - mariadb
        build: ./requirements/wordpress
        image: wordpress:kankim
        container_name: wordpress
        restart: always
        volumes:
            - type: volume
              source: website
              target: /var/www
        networks:
            - networks
        tty: true
        env_file: 
            - .env

    mariadb:
        build: ./requirements/mariadb
        image: mariadb:kankim
        container_name: mariadb
        restart: always
        volumes:
            - type: volume
              source: database
              target: /var/lib/mysql
        networks:
            - networks
        tty: true
        env_file: 
            - .env
