version: '3'

volumes:
    data: {}

networks:
    intra:
        driver: bridge

services:
    nginx:
        depends_on: 
            - wordpress
        build: ./requirements/nginx
        image: nginx:kankim
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - data:/var/www/html
        networks:
            - intra
        tty: true

    wordpress:
        depends_on: 
            - mariadb
        build: ./requirements/wordpress
        image: wordpress:kankim
        container_name: wordpress
        restart: always
        volumes:
            - data:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true

    mariadb:
        build: ./requirements/mariadb
        image: mariadb:kankim
        container_name: mariadb
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        tty: true
