version: '3'

networks:
    networks:

volumes:
    database:
        name: database
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/kankim/data/database
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/kankin/data/wordpress

services:
    nginx:
        depends_on: 
            - wordpress
        build: ./requirements/nginx
        image: nginx:kankim
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - networks
        tty: true
        env_file: 
            - .env
    wordpress:
        depends_on: 
            - mariadb
        build: ./requirements/wordpress
        image: wordpress:kankim
        container_name: wordpress
        restart: always
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - networks
        tty: true
        env_file: 
            - .env
    mariadb:
        build: ./requirements/mariadb
        image: mariadb:kankim
        container_name: mariadb
        restart: always
        volumes:
            - database:/var/lib/mysql
        networks:
            - networks
        tty: true
        env_file: 
            - .env
