mysql -u root -p"$ROOT_PASS"<<-EOSQL
	CREATE DATABASE $DB_NAME;
	CREATE USER "$DB_USER"@"%" IDENTIFIED BY "$DB_PASS";
	GRANT ALL PRIVILEGES ON $DB_NAME.* TO "$DB_USER"@"%";
	FLUSH PRIVILEGES;
	SET PASSWORD FOR 'root'@'localhost' = PASSWORD("$ROOT_PASS");
EOSQL